# Generated by Django 3.2.12 on 2022-05-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220427_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default='May 03, 2022 15:20:19'),
        ),
    ]
